openapi: 3.1.1
info:
  title: Smart-ID Automated Testing Interface
  version: 1.0.0
  description: "Smart-ID helper API for automated testing of RP API v3 device link flows. \nFor background and usage guidance, it is recommended to first read the [Introduction](./mock_service.html) to the Mock Service. \n\nIn order to test their implementation in the demo environment, RPs should initially create the session via RP API in the usual way. \nThen (in the case of device link flows), the API endpoint described below should be used to simulate the mobile device interaction (Web2App, App2App, or QR). \nAfter that, the session will be resolved with a predetermined result based on the provided test document number.\nFinally, the session result can be obtained via RP API, as usually.\n"
  contact:
    name: SK ID Solutions
    url: https://www.skidsolutions.eu/
    email: support@smart-id.com
  license:
    name: Proprietary license
    url: https://smart-id.com
  termsOfService: https://www.skidsolutions.eu/resources/general-terms-of-subscriber-agreement/
servers:
- url: https://sid.demo.sk.ee/mock
tags:
- name: Device Link
  description: API endpoint for submitting device links to the automated testing interface
paths:
  /device-link:
    post:
      tags:
      - Device Link
      summary: API endpoint for submitting device links to the automated testing interface
      description: |-
        For a general overview of the testing environment and its purpose, see [Introduction](./mock_service.html) to the Mock Service.
        For details on how device links are generated and used in authentication/signing flows, see [Device link flow](./device_link_flows.html).
      operationId: sendDeviceLink
      requestBody:
        $ref: '#/components/requestBodies/DeviceLinkRequestBody'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Client error.
components:
  schemas:
    DocumentNumber:
      type: string
      description: One of the configured document numbers. Each resolves with a specific resultType. Mandatory and must be provided even for anonymous sessions, because this will determine the resultType. See [Test accounts](../test_accounts.html) for available values.
    DeviceLink:
      type: string
      description: Device link (Web2App link, App2App link, or the device link contained in a QR code) that the user would normally interact with in a live environment. In the automated testing interface, this interaction is simulated by sending the device link to this endpoint instead. The link should be constructed using the same principles as in the live environment and must correspond to the selected flowType. The provided device link will be associated with the specified documentNumber to simulate the transaction outcome.
      format: URL
    FlowType:
      type: string
      description: Specifies which device link flow the automated testing interface will simulate. The provided deviceLink must correspond to the selected flow type.
      enum:
      - Web2App
      - App2App
      - QR
    BrowserCookie:
      type: string
      description: A string or stringified JSON of the cookie value that RP would have set to user's browser if this was a user-initiated session. Required if flowType is Web2App or App2App. Should be ignored if flowType is QR.
    InitialCallbackUrl:
      type: string
      description: The callback URL the automated testing interface will add parameters to and launch after a successful Web2App or App2App flow. Mandatory if Web2App and App2App flows are used, ignored for QR flow.
      format: URL
  requestBodies:
    DeviceLinkRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
            - documentNumber
            - deviceLink
            - flowType
            properties:
              documentNumber:
                $ref: '#/components/schemas/DocumentNumber'
              deviceLink:
                $ref: '#/components/schemas/DeviceLink'
              flowType:
                $ref: '#/components/schemas/FlowType'
              browserCookie:
                $ref: '#/components/schemas/BrowserCookie'
              initialCallbackUrl:
                $ref: '#/components/schemas/InitialCallbackUrl'
          examples:
            Device Link Authentication Request Example:
              $ref: '#/components/examples/DeviceLinkRequestBodyExample'
  examples:
    DeviceLinkRequestBodyExample:
      value:
        documentNumber: PNOEE-40404040009-MOCK-Q
        deviceLink: https://sid.demo.sk.ee/device-link/?...
        flowType: Web2App
        browserCookie: a=b;c=d
        initialCallbackUrl: https://rp.example.com/callback-url?value=RrKjjT4aggzu27YBddX1bQ
