= Welcome to Smart-ID demo page

This page will give you short overview of the Smart-ID and help you get started.

== Smart-ID description

Smart-ID is the next generation solution for managing your identity online. With Smart-ID you can log into 3rd party websites and give legally valid digital signature. Smart-ID works in your mobile phone or tablet and doesn't require specially issued SIM-card.

The demo version has the following functionality:

. User can use Smart-ID to log into the website (bank123 demo portal).
. User can log in Smart-ID self-service portal https://sid.demo.sk.ee/portal and get an overview of accounts and to delete an account.
. User can log in to any test e-service which is integrated with Smart-ID demo service.

== Getting started

For using demo environment there is need to install Smart-ID demo app.

Getting Smart-ID up and running is easy. Follow those easy 4 steps:

. **Registration & Installation**
.. Install demo app on Android platform (minimum Android 5 required): https://play.google.com/apps/testing/com.stagnationlab.sk
.. Steps to install on iOS (minimum iOS13 required):
... Download Testflight https://itunes.apple.com/us/app/testflight/id899247664?mt=8
... Join Smart-ID demo beta app in https://testflight.apple.com/join/DoWddZjR
. **Start the app**
.. Start the Smart-ID app and choose the Register button.
. **Prove your identity**
.. For beta version, you can choose to prove your identity via provided bank links.
.. Just make your selection, and you'll be redirected to the bank's Internet bank, and you are asked to log in with different tokens.
... Using bank link as a registration method means, that you will be granted Smart-ID Basic account.
... Using ID-card or mobile-ID means, that you will be receiving a Smart-ID Qualified account. Smart-ID Basic can be used only by IDP-s (banks), so we suggest preferring ID-card or Mobile-ID as a registration.
.. After successful login, you'll arrive back in the app, just confirm that your name and national identification number is correct.
.. If you don't have supported bank account, you can still try out the app by entering your personal data manually.
... If you do have Estonian personal ID-code, then you are not eligible for manual registration. Use 'Other country' instead if you prefer manual registration. Negative side here is, that you will receive randomly generated personal code, which makes testing more difficult (have to remember that personal code).
. **Enter your PIN1 and PIN2**
.. The app asks for your PIN1 and PIN2 code. PIN1 is for protecting your authentication key pair and PIN2 is for protecting your signature key pair, same way as with ID-card and Mobile-ID.
.. You can choose the random codes, generated by app, or enter your own favorite PIN code
.. Either way, make sure you remember the codes afterwards.
. **Install sample bank123 app** +
App demonstrates 
ifeval::["{service-name}" != ""]
xref:rp-api:ROOT:overview.adoc#same_device_use_cases[same device usecase]
endif::[]
ifeval::["{service-name}" == ""]
https://sk-eid.github.io/smart-id-documentation/rp-api/overview.html#same_device_use_cases[same device usecase]
endif::[]
how Smart-ID app is automatically opened from another app.
.. Get app for Android platform
... Join on Android https://play.google.com/store/apps/details?id=com.smart_id.bank123
... Join on the web https://play.google.com/apps/testing/com.smart_id.bank123
.. Get app for iOS platform by joining  https://testflight.apple.com/join/oAeBWz8l


Your Smart-ID account is now ready to use. If you have iOS watch with watchOS 8.5 or later, then you can test Smart-ID from the watch as well.

== Try it out

To see the Smart-ID in action and to actually use it to log into a website and give the digital signature, you can try the following beta services.

. https://smid.demo.sk.ee/#login[https://smid.demo.sk.ee] Bank123 demo portal to demonstrate Smart-ID for online banking services
. https://beta.dokobit.com/login[https://beta.dokobit.com/] Dokobit BETA to demonstrate Smart-ID usage for signing
. https://sid.demo.sk.ee/portal/login[https://sid.demo.sk.ee/portal/login] Smart-ID demo portal
.. Cross-device QR flow
... Open page from computer browser → “Enter Smart-ID portal (Smart-ID)” → "Sign in using Smart-ID QR code" 
... Open Smart-ID app and press button “Scan QR code” to init QR scanner and scan the QR code.
.. Same-device web2app flow
... Open page from phone browser →“Enter Smart-ID portal (Smart-ID)” → “Open Smart-ID app”
... Smart-ID app is opened automatically.
. Bank123 app
.. Same-device app2app flow
... Open Bank123 app
... Press “Log in & open Smart-ID”
... Bank123 will initiate app2app login and open Smart-ID app with app2app link.

.NOTE
[NOTE]
====
For demo purposes, some of the security features of the Smart-ID demo environment are not identical with the production environment. The Smart-ID demo environment is not intended to be used for security testing.
====

.NOTE
[NOTE]
====
Smart-ID demo certificates are not automatically available for DEMO AIA OCSP - aia.demo.sk.ee
====

* There is a special interface that enables uploading certificates with an option to set the status. The upload page is available at https://demo.sk.ee/upload_cert/.
* Smart-ID demo certificates can be downloaded from https://sid.demo.sk.ee/portal/login
* Additional info about DEMO OCSP https://github.com/SK-EID/ocsp/wiki/SK-OCSP-Demo-environment

== Give us feedback
xref:contact.adoc[Contact]

All feedback to the Smart-ID DEMO version is much appreciated. Please send it to the e-mail address mailto:support@sk.ee?subject=Smart-ID%20DEMO%20feedback[support@sk.ee].

When you report a problem, please include at least the following information:

* E-mail subject: Smart-ID DEMO feedback
* detailed description of the problem (if possible with screenshots)
* date and time when the problem occurred
* your device model and version of the operating system
* your personal code
* your account UUID, you will find it on Smart-ID App account management section
