= OpenAPI specification
:page-ui: api

[subs="attributes"]
++++
<div id="app"></div>

<script>
    Scalar.createApiReference('#app', {
    url: './_/static/autosigner.yml',
    showSidebar: true,
    hideModels: true,
    withDefaultFonts: false,
    darkMode: false,
    hideDarkModeToggle: true,
    forceDarkModeState: 'light',
    hideDarkModeToggle: true,
    hideClientButton: true,
    customCss: `
    #app {
        --scalar-color-1: var(--caption-font-color);
        --scalar-color-2: var(--body-font-color);
        --scalar-link-color: var(--link-font-color);
        --scalar-link-color-hover: var(--link_hover-font-color);
        --scalar-border-color: var(--panel-border-color);
        --scalar-font: 'Inter Variable', sans-serif;
        --scalar-font-code: 'Roboto Mono Variable', monospace;
        --scalar-micro: 13px;
    }

    .scalar-app .dark-mode {
        --scalar-background-1: var(--color-neutral-950);
        --scalar-background-2: var(--pre-background);
        --scalar-background-3: var(--color-neutral-900);
        --scalar-border-color: var(--pre-border-color);
    }

    .scalar-app .introduction-section {
        padding-top: 32px;
    }

    .scalar-app .section-header {
        color: var(--heading-font-color);
    }

    .scalar-app .parameter-list-title,
    .scalar-app .request-body-title {
        color: var(--heading-font-color);
        font-size: 1.125rem;
        font-weight: var(--body-font-weight-semibold);
    }

    .scalar-app .introduction-section .section-header {
        font-size: 1.875rem;
        letter-spacing: -0.05rem;
        margin-top: 4px;
    }

    .scalar-app .section-container {
        padding: 0 40px;
    }
    
    .scalar-app .scalar .scalar-app-layout {
        height: calc(100% - 48px);
        max-width: calc(100% - 48px);
        border-color: transparent;
    }

    .scalar-app .fade-request-section-content {
        background: none;
    }

    .scalar-app .scalar .scalar-app-exit {
        background: #00000096;
    }

    .scalar-app .markdown p {
        line-height: 1.75;
    }

    .scalar-app .markdown h1,
    .scalar-app .markdown h2,
    .scalar-app .markdown h3,
    .scalar-app .markdown h4,
    .scalar-app .markdown h5,
    .scalar-app .markdown h6,
    .scalar-app .markdown p,
    .scalar-app .markdown div,
    .scalar-app .markdown img,
    .scalar-app .markdown details,
    .scalar-app .markdown summary,
    .scalar-app .markdown ul,
    .scalar-app .markdown ol,
    .scalar-app .markdown table,
    .scalar-app .markdown blockquote,
    .scalar-app .markdown code {
        margin: 16px 0;
    }

    .scalar-app .app-exit-button {
        background: #00000098;
    }

    .scalar-app .app-exit-button:hover {
        background: #000;
    }

    .scalar-app .darklight-reference {
        display: none;
    }

    .scalar-app .show-more {
        background-color: #fff;
    }

    .scalar-app .scalar-api-references-standalone-search {
        padding: 72px 16px 8px 16px
    }

    .scalar-app .sidebar-pages {
        padding: 8px 16px 64px 16px
    }

    .scalar-app .scalar-modal-search {
        min-width: 960px;
    }

    .scalar-app .scalar-address-bar {
        --scalar-address-bar-height: 40px;
        width: 90%;
    }

    .scalar-app .address-bar-bg-states {
        min-width: unset !important;
        max-width: 100% !important;
    }

    @media screen and (max-width: 1000px) {

        .scalar-app .scalar-api-references-standalone-search {
            padding: 8px 16px 8px 16px
        }

        .scalar-app .sidebar-pages {
            padding: 8px 16px 8px 16px
        }

        .scalar-app .section-container {
            padding-inline: 0;
        }

        .scalar-app .section-container .section {
            padding-inline: 16px;
        }

        .scalar-app .scalar-address-bar {
            --scalar-address-bar-height: 32px;
            padding-inline: 40px;
            margin-top: -8px;
            width: 100%;
        }
    }

`,
    });
    document.addEventListener('DOMContentLoaded', function() {
        const backLinks = document.querySelectorAll('.nav-back-link');
        const currentDomain = window.location.hostname;
        backLinks.forEach(link => {
            link.addEventListener('click', function(event) {
                event.preventDefault();
                const referrer = document.referrer;
                let referrerDomain = null;
                if (referrer) {
                    try {
                        const referrerUrl = new URL(referrer);
                        referrerDomain = referrerUrl.hostname;
                    } catch (e) {
                        console.error("Invalid referrer URL:", referrer, e);
                        referrerDomain = null;
                    }
                }
                const shouldFallbackToHref = history.length <= 1 || !referrer || referrerDomain !== currentDomain;
                if (shouldFallbackToHref) {
                    window.location.href = link.href;
                } else {
                    history.back();
                }
            });
        });
    });
    document.addEventListener('DOMContentLoaded', function() {
        document.body.addEventListener('click', function(event) {
            const targetLink = event.target.closest('.sidebar-heading-link');
            if (targetLink) {
                event.preventDefault();
                const url = targetLink.getAttribute('href');
                if (url) {
                    history.replaceState({}, '', url);
                    window.location.replace(url);
            }
            }
        });
    });

</script>
++++

// Scalar configuration:
// https://github.com/scalar/scalar/blob/main/documentation/configuration.md