= Test accounts for automated testing

== Device link flows
See 
ifeval::["{service-name}" != ""]
xref:rp-api:ROOT:mock_service.adoc[more] 
endif::[]
ifeval::["{service-name}" == ""]
https://sk-eid.github.io/smart-id-documentation/rp-api/mock_service.html[more]
endif::[]
how to test device-link flows 

[cols="2m,1,3,3", options="header", stripes=odd, grid=none, frame=none]
|===
| EndResult | Country | Document Number | Comment
| OK | EE +
LT +
LV +
BE  
| PNOEE-40404040009-MOCK-Q +
PNOLT-40404040009-MOCK-Q +
PNOLV-040404-10003-MOCK-Q +
PNOBE-04040400287-MOCK-Q
| Adult
| OK | EE +
LT +
LV +
LV +
BE
| PNOEE-61101019999-MOCK-Q +
PNOLT-61101019999-MOCK-Q +
PNOLV-020211-12343-MOCK-Q +
PNOLV-320000-00008-MOCK-Q +
PNOBE-11010199815-MOCK-Q
| Minor
| OK | LT +
LV 
| PNOLT-61101019988-MOCK-NQ +
PNOLV-020211-12351-MOCK-NQ
| Minor
|===


== Notification flows

[cols="2m,1,3,3", options="header", stripes=odd, grid=none, frame=none]
|===
| EndResult | Country | Document Number | Comment
| OK | EE +
LT +
LV +
LV +
BE | PNOEE-40504040001-DEMO-Q +
PNOLT-40504040001-MOCK-Q +
PNOLV-050405-10009-DEMO-Q +
https://www.pmlp.gov.lv/en/change-personal-identity-number[PNOLV-320000-10003-MOCK-Q] +
PNOBE-05040400032-DEMO-Q | Issued using: +
**TEST of SK ID Solutions EID-Q 2024E**
| OK | LT +
LV | PNOLT-40504049999-MOCK-NQ +
PNOLV-050404-19993-DEMO-NQ | Issued using: +
**TEST of SK ID Solutions EID-NQ 2021E**
| OK | EE +
LT +
LV +
BE | PNOEE-50001029996-DEMO-Q +
PNOLT-50001029996-DEMO-Q +
PNOLV-020100-29990-MOCK-Q +
PNOBE-00010299944-MOCK-Q | Adult
| OK | LT | PNOLT-30303039914-MOCK-Q |
| OK | EE +
LT +
LV +
BE | PNOEE-39901012239-MOCK-Q +
PNOLT-39901012239-DEMO-Q +
PNOLV-030303-10215-MOCK-Q +
PNOBE-99010199987-DEMO-Q | User has other active account
| OK | EE +
LT +
LV +
LV| PNOEE-61101012257-MOCK-Q +
PNOLT-61101012257-MOCK-Q +
PNOLV-010111-23474-DEMD-Q +
PNOLV-320000-00032-MOCK-Q | User age is under 18 (2011-01-01)
| OK | LV | PNOLV-030303-10004-MOCK-Q | No numbers in names
| OK | LV | PNOLV-040404-19999-MOCK-Q |
| OK | LV | PNOLV-040404-19980-MOCK-Q |
| OK | LV | PNOLV-311299-19993-MOCK-Q +
PNOLV-329999-99901-MOCK-Q | dateOfBirth in separate field
| OK | LV | PNOLV-329999-99709-MOCK-Q | No dateOfBirth in separate field
| OK | LT +
LV | PNOLT-49912318881-MOCK-NQ +
PNOLV-311299-18886-MOCK-NQ |
| USER_REFUSED | EE +
LT +
LV +
BE | PNOEE-30403039917-MOCK-Q +
 PNOLT-30403039917-MOCK-Q +
 PNOLV-030403-10016-MOCK-Q +
PNOBE-00010238349-MOCK-Q |
| USER_REFUSED +
_DISPLAYTEXTANDPIN | EE +
LT +
LV +
BE | PNOEE-30403039928-MOCK-Q +
PNOLT-30403039928-MOCK-Q +
PNOLV-030403-10024-MOCK-Q +
PNOBE-00010267350-MOCK-Q | v1 response USER_REFUSED
| USER_REFUSED +
_VC_CHOICE | EE +
LT +
LV +
BE |PNOEE-30403039939-MOCK-Q +
PNOLT-30403039939-MOCK-Q +
PNOLV-030403-10032-MOCK-Q +
PNOBE-00010266756-MOCK-Q | v1 response USER_REFUSED
| USER_REFUSED +
_CONFIRMATIONMESSAGE|EE +
LT +
LV +
BE| PNOEE-30403039946-MOCK-Q +
PNOLT-30403039946-MOCK-Q +
PNOLV-030403-10040-MOCK-Q +
PNOBE-00010232708-MOCK-Q | v1 response USER_REFUSED
| USER_REFUSED +
_CONFIRMATIONMESSAGE +
_WITH_VC_CHOICE |EE +
LT +
LV +
BE| PNOEE-30403039950-MOCK-Q +
PNOLT-30403039950-MOCK-Q +
PNOLV-030403-10059-MOCK-Q +
PNOBE-00010211724-MOCK-Q | v1 response USER_REFUSED
| WRONG_VC |EE +
LT +
LV +
BE|PNOEE-30403039972-MOCK-Q +
PNOLT-30403039972-MOCK-Q +
PNOLV-030403-10075-MOCK-Q +
PNOBE-00010216276-MOCK-Q |
| TIMEOUT |EE +
LT +
LV +
BE| PNOEE-30403039983-MOCK-Q +
PNOLT-30403039983-MOCK-Q +
PNOLV-030403-10083-MOCK-Q +
PNOBE-00010220335-MOCK-Q |
|===
